name       : lxc
version    : 2.1.1
release    : 5
source     :
    - https://github.com/lxc/lxc/archive/lxc-2.1.1.tar.gz : eb36670acb50babf375e79028316c5c92e07c9d84e0cb1a0ae86ed3dbbb13075
license    : LGPL-2.1-or-later
component  : virt
summary    : Linux Containers
description: |
    LXC is the well known set of tools, templates, library and language bindings. It's pretty low level, very flexible and covers just about every containment feature supported by the upstream kernel.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(libapparmor)
    - pkgconfig(libcap)
    - pkgconfig(libcgmanager)
    - pkgconfig(libnih)
    - pkgconfig(libseccomp)
    - pkgconfig(lua-5.3)
    - pkgconfig(python-3.6)
setup      : |
    %reconfigure --disable-static \
                 --with-init-script=systemd \
                 --with-systemdsystemunitdir=/usr/lib/systemd/system
build      : |
    %make
install    : |
    %make_install
