name       : lxc
version    : 2.1.1
release    : 4
source     :
    - https://linuxcontainers.org/downloads/lxc/lxc-2.1.1.tar.gz : 68663a67450a8d6734e137eac54cc7077209fb15c456eec401a2c26e6386eff6
license    : LGPL-2.1
component  : virt
summary    : Linux Containers
description: |
    LXC is the well known set of tools, templates, library and language bindings. It's pretty low level, very flexible and covers just about every containment feature supported by the upstream kernel.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(libapparmor)
    - pkgconfig(libcap)
    - pkgconfig(libcgmanager)
    - pkgconfig(libnih)
    - pkgconfig(libseccomp)
    - pkgconfig(lua-5.3)
    - pkgconfig(python-3.6)
setup      : |
    %configure --disable-static \
               --with-init-script=systemd \
               --with-systemdsystemunitdir=/usr/lib/systemd/system
build      : |
    %make
install    : |
    %make_install
