name       : lxc
version    : 5.0.2
release    : 18
source     :
    - https://linuxcontainers.org/downloads/lxc/lxc-5.0.2.tar.gz : bea08d2e49efcee34fa58acd2bc95c0adc64d291c07f4cfaf4ac1d8ac5a36f45
license    : LGPL-2.1-or-later
component  : virt
summary    : Linux Containers
description: |
    LXC is the well known set of tools, templates, library and language bindings. It's pretty low level, very flexible and covers just about every containment feature supported by the upstream kernel.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(libapparmor)
    - pkgconfig(libcap)
    - pkgconfig(libseccomp)
    - pkgconfig(lua-5.3)
    - pkgconfig(python3)
    - docbook2x
setup      : |
    sed -i "s|if sanitize == 'none'|if false|g" src/lxc/cmd/meson.build

    %meson_configure -Ddistrosysconfdir=/etc/default
build      : |
    %ninja_build
install    : |
    %ninja_install
