name       : lxc
version    : 5.0.1
release    : 16
source     :
    - https://linuxcontainers.org/downloads/lxc/lxc-5.0.1.tar.gz : d8195423bb1e206f8521d24b6cde4789f043960c7cf065990a9cf741dcfd4222
license    : LGPL-2.1-or-later
component  : virt
summary    : Linux Containers
description: |
    LXC is the well known set of tools, templates, library and language bindings. It's pretty low level, very flexible and covers just about every containment feature supported by the upstream kernel.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(libapparmor)
    - pkgconfig(libcap)
    - pkgconfig(libseccomp)
    - pkgconfig(lua-5.3)
    - pkgconfig(python3)
    - docbook2x
setup      : |
    %apply_patches
    sed -i "s|if sanitize == 'none'|if false|g" src/lxc/cmd/meson.build
    
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
