name       : lxc
version    : 4.0.6
release    : 9
source     :
    - https://github.com/lxc/lxc/archive/lxc-4.0.6.tar.gz : 360e98bc2a1aa07a78ecaacf876ccc23ef953218443671cc7db1dc0bb3779d1d
license    : LGPL-2.1-or-later
component  : virt
summary    : Linux Containers
description: |
    LXC is the well known set of tools, templates, library and language bindings. It's pretty low level, very flexible and covers just about every containment feature supported by the upstream kernel.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(libapparmor)
    - pkgconfig(libcap)
    - pkgconfig(libcgmanager)
    - pkgconfig(libnih)
    - pkgconfig(libseccomp)
    - pkgconfig(lua-5.3)
    - pkgconfig(python3)
setup      : |
    %reconfigure --disable-static \
                 --with-init-script=systemd \
                 --with-systemdsystemunitdir=/usr/lib/systemd/system
build      : |
    %make
install    : |
    %make_install
