name       : lxc
version    : 1.1.5
release    : 1
source     :
    - https://linuxcontainers.org/downloads/lxc/lxc-1.1.5.tar.gz : 9588ad1b04e114ee7370f690c65131e28098b28d2521d97c73557d11897ed0be
license    : LGPL-2.1
summary    : Linux Containers
description: |
    LXC is the well known set of tools, templates, library and language bindings. It's pretty low level, very flexible and covers just about every containment feature supported by the upstream kernel.
builddeps  :
    - pkgconfig(libseccomp)
    - pkgconfig(libcgmanager)
    - pkgconfig(libnih)
    - pkgconfig(dbus-1)
    - pkgconfig(python-3.4)
    - pkgconfig(lua-5.1)
    - libcap2-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
