name       : lxc
version    : 4.0.11
release    : 12
source     :
    - https://github.com/lxc/lxc/archive/lxc-4.0.11.tar.gz : 27e9b5232453239be0310d7f33857c06bfcfce92c31c87defa73a4e6d6e0726e
license    : LGPL-2.1-or-later
component  : virt
summary    : Linux Containers
description: |
    LXC is the well known set of tools, templates, library and language bindings. It's pretty low level, very flexible and covers just about every containment feature supported by the upstream kernel.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(libapparmor)
    - pkgconfig(libcap)
    - pkgconfig(libseccomp)
    - pkgconfig(lua-5.3)
    - pkgconfig(python3)
setup      : |
    %patch -p1 < $pkgfiles/0001-conf-handle-kernels-without-or-not-using-SMT.patch
    export CFLAGS="${CFLAGS//-Wall /}"
    %reconfigure --with-distro=solus \
                 --disable-static \
                 --with-init-script=systemd \
                 --with-systemdsystemunitdir=/usr/lib/systemd/system
build      : |
    %make
install    : |
    %make_install
