name       : lxc
version    : 3.2.1
release    : 7
source     :
    - https://github.com/lxc/lxc/archive/lxc-3.2.1.tar.gz : 59f46fad0a6d921c59a6768ba781295e0986989a96e2d216de2b4b3a14392e65
license    : LGPL-2.1-or-later
component  : virt
summary    : Linux Containers
description: |
    LXC is the well known set of tools, templates, library and language bindings. It's pretty low level, very flexible and covers just about every containment feature supported by the upstream kernel.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(libapparmor)
    - pkgconfig(libcap)
    - pkgconfig(libcgmanager)
    - pkgconfig(libnih)
    - pkgconfig(libseccomp)
    - pkgconfig(lua-5.3)
    - pkgconfig(python-3.6)
setup      : |
    %patch -p1 < $pkgfiles/uninitialized.patch
    %reconfigure --disable-static \
                 --with-init-script=systemd \
                 --with-systemdsystemunitdir=/usr/lib/systemd/system
build      : |
    %make
install    : |
    %make_install
