name       : lxc
version    : 4.0.12
release    : 13
source     :
    - https://github.com/lxc/lxc/archive/lxc-4.0.12.tar.gz : d0549ffbc0c920416d7842030091353b3ddf44d577b42e4f899d3440d6b373f2
license    : LGPL-2.1-or-later
component  : virt
summary    : Linux Containers
description: |
    LXC is the well known set of tools, templates, library and language bindings. It's pretty low level, very flexible and covers just about every containment feature supported by the upstream kernel.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(libapparmor)
    - pkgconfig(libcap)
    - pkgconfig(libseccomp)
    - pkgconfig(lua-5.3)
    - pkgconfig(python3)
setup      : |
    export CFLAGS="${CFLAGS//-Wall /}"
    %reconfigure --with-distro=solus \
                 --disable-static \
                 --with-init-script=systemd \
                 --with-systemdsystemunitdir=/usr/lib/systemd/system
build      : |
    %make
install    : |
    %make_install
