name       : lxc
version    : 4.0.9
release    : 11
source     :
    - https://github.com/lxc/lxc/archive/lxc-4.0.9.tar.gz : b841deaffca440de990181c6e423cfe700eebc40b239682efc36aa6a0ff0553c
license    : LGPL-2.1-or-later
component  : virt
summary    : Linux Containers
description: |
    LXC is the well known set of tools, templates, library and language bindings. It's pretty low level, very flexible and covers just about every containment feature supported by the upstream kernel.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(libapparmor)
    - pkgconfig(libcap)
    - pkgconfig(libcgmanager)
    - pkgconfig(libnih)
    - pkgconfig(libseccomp)
    - pkgconfig(lua-5.3)
    - pkgconfig(python3)
setup      : |
    # Kernel 5.12 compatibility
    %patch -p1 < $pkgfiles/0001-conf-handle-kernels-with-CAP_SETFCAP.patch

    %reconfigure --disable-static \
                 --with-init-script=systemd \
                 --with-systemdsystemunitdir=/usr/lib/systemd/system
build      : |
    %make
install    : |
    %make_install
